POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Liam Sy 3",
  "number": "123456"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Liam Sy"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "number": "123456"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
}

###

GET http://localhost:3001/api/persons

###

PUT http://localhost:3001/api/persons/62e5c92f3d05e99917773759
content-type: application/json

{
  "name": "Liam Sy 3",
  "number": "12345641241"
}